version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
  backend:
    build: ./urlshortener
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend